### PR TITLE
Feedback hw02

### PR DESCRIPTION
**Pull request by bwiernik**
Good work! Please see my comments marked with BMW

Let's set up a call to walk through how to resolve merge conflicts.

### CODE REVIEW

**Comment by whitneykasenetz** [comment]
merge feedback 2

**Comment by bwiernik** [comment]
You didn't merge this.

**Comment by whitneykasenetz** [comment]
> You didn't merge this.

I'm silly. Thank you!

**Comment by bwiernik** [comment]
👍🏼

**Pull request merged**
